polaris/contact/urls.py
from django.urls import path

from . import views

app_name = "contact"

urlpatterns = [
	path('',views.index,name='index'),
	path('success/',views.success,name='success')
]

polaris/polaris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from polaris import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('world/',include('world.urls')),
	path('contact/',include('contact.urls')),
	path('',views.home,name='home')
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polaris/world/urls.py
from django.urls import path

from . import views

app_name = 'world'

urlpatterns = [
	path('',views.index,name='index'),
	path('world_view/',views.world_view,name='world_view')
]

polaris/contact/models.py
from django.db import models
from django.utils.timezone import now

class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField()
	message=models.TextField()
	timestamp = models.DateTimeField(default=now())

	def __str__(self):
		return self.name + ', ' + self.email + ', submitted on ' + self.timestamp.strftime("%Y-%m-%d %H:%M")

# Create your models here.

polaris/contact/forms.py
from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model=Contact
		fields=('name','email','message',)

polaris/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from contact.forms import ContactForm
from django.utils.timezone import now
from django.shortcuts import redirect
def index(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.timestamp = now()
			post.save()
			return redirect('contact:success')
	form = ContactForm()
	return render(request,'contact/Contact.html',{'form':form})
def success(request):
	return render(request,'contact/success.html',{})

# Create your views here.

polaris/polaris/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
	return render(request,'polaris/home.html')

polaris/world/views.py
from django.shortcuts import render
from django.http import HttpResponse
from world.read import pandas_chunks
from random import randint
import pandas as pd
from dateparser import parse
import datetime
import time

#accesses datapoint directly without chunksize
#faster, but won't work with larger dataset
def old_read(request):
	#moved above as a global var
	data_df = pd.read_json('/run/media/brianl/SAMSUNG USB/RideCommandForHack_example.json',lines=True)
	print('json file loaded')

	#opens the JSON files, extracts a random point, and extacts the lat/long coords, time/distance, and start-end timestamp
	print('page loading started')
	datapoint = data_df.iloc[randint(0,len(data_df))]
	print(type(datapoint))
	print('specific data point isolated')


def index(request):

	start_time = time.time()

	datapoint = pandas_chunks('/run/media/brianl/SAMSUNG USB/RideCommandForHack.json')
	properties = datapoint.properties
	print('properties apect extracted')

	side_values = {'totalDurationInSeconds':int(properties['totalDurationInSeconds']),'totalDistanceInMeters':round(properties['totalDistanceInMeters'],2)}
	try:
		side_values['startTimestamp']=parse(str(properties['startTimestamp']['$date']))
		side_values['endTimestamp']=parse(str(properties['endTimestamp']['$date']))
	except:
		side_values['startTimestamp']='N/A'
		side_values['endTimestamp']='N/A'
	print('side_values dictionary created')

	coords = datapoint.geometry['coordinates']
	print('coordinates list extracted')

	sum_long = 0
	sum_lat = 0
	for coord in coords:
		sum_long+=coord[0]
		sum_lat+=coord[1]
	print('average coords calculated')

	end_time = time.time()

	return render(request,'world/map.html',{'coords':coords,'avg_long':sum_long/len(coords),'avg_lat':sum_lat/len(coords),'side_values':side_values,'time_calc':int(end_time-start_time)})
# Create your views here.

def world_view(request):
	data_df = pd.read_json('/run/media/brianl/SAMSUNG USB/RideCommandForHack_example.json',lines=True) #copied from old_read
	average_points = []
	print(data_df.columns)
	for datapoint in data_df.geometry:
		print(type(datapoint))
		sum_long =0
		sum_lat = 0
		for coord in datapoint['coordinates']:
			sum_long+=coord[0]
			sum_lat+=coord[1]
		average_points.append([sum_long/len(datapoint['coordinates']),sum_lat/len(datapoint['coordinates'])])
	print(len(average_points))
	return render(request,'world/world_view.html',{'average_points':average_points})

polaris/contact/templates/contact/Contact.html
{% extends 'polaris/index.html' %}
{% load bootstrap4 %}
		{% block title %}Contact Us{% endblock %}
		{% block body %}
			<!--
			<div>
				<p id="shadow2"><form action="" method="post" class="elegant-aero">
					<h1>Contact Form 
						<span>Please fill all the texts in the fields.</span>
					</h1>
					<label>
						<span>Your Name :</span>
						<input id="name" type="text" name="name" placeholder="Your Full Name" />
					</label>
					
					<label>
						<span>Your Email :</span>
						<input id="email" type="email" name="email" placeholder="Valid Email Address" />
					</label>
					
					<label>
						<span>Message :</span>
						<textarea id="message" name="message" placeholder="Your Message to Us"></textarea>
					</label> 
					<label>
						<span>&nbsp;</span> 
						<input type="button" class="button" value="Send" /> 
					</label>    
				</form>
				</div>
			</p>
		</div>
		-->
		<div class = "container">
		<div class = "jumbotron text-center"><h1>Contact Us</h1></div>
		<form method = "POST" class = "form text-center" style = "margin:1rem">{% csrf_token %}
			{% bootstrap_form form %}
			{% buttons %}
				<button type="submit" class="btn btn-primary">Save</button>
			{% endbuttons %}
		</form>

		<center>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2952.429147830323!2d-83.7446531841953!3d42.26936177919309!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883cae3636c5c47d%3A0x4488bf86906b1fc8!2sIntramural+Sports+Building!5e0!3m2!1sen!2sus!4v1539457887153" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</center>
		</div>
		{% endblock %}	

polaris/contact/templates/contact/success.html
{% extends 'polaris/index.html' %}
{% block title %}Question Submitted!{% endblock %}
{% block body%}
<div class = "container">
	<div class = "jumbotron"><h1>Thank you for for your question!</h1></div>
	<h2>We will get back to you via the email you submitted</h2>
	<img src = "https://images-na.ssl-images-amazon.com/images/I/81uoY87t8lL._SX679_.jpg" class = "img img-responsive mx-auto d-block">
</div>
{% endblock %}

polaris/templates/polaris/About.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Polaris Data</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
		<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
		<link href="style.css" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
			<div class="container-fluid">
				<a class=""navbar-brand" href="#"><img src="http://brand.polaris.com/wp-content/uploads/2015/11/Polaris_corpId_logos_flat_696x150.png" style="width:150px;height:40px">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="index.html">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="About.html">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Google Data</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="Contact.html">Contact Us</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<footer>
			<div class="container-fluid padding">
				<div class="row text-center">
					<div class="col-md-4">
						<img src="http://brand.polaris.com/wp-content/uploads/2015/11/Polaris_corpId_logos_flat_696x150.png" style="width:150px;height:40px">
						<hr class="light">
						<p>734-642-3511</p>
						<p>MHACKS11_Polaris@Mhacks.com</p>
						<p>606 E Hoover Ave</p>
						<p>Ann Arbor,MI 48104</p>
					</div>
					<div class="col-md-4">
						<hr class="light">
						Navagation
						<hr class="light">
						<div id="containers">
							<nav>
								<ul>
									<li><a class="active" href="index.html">Home</a></li>
									<li><a href="About.html">About</a></li>
									<li><a href="#">Google Data</a></li>
									<li><a href="Contact.html">Contact</a></li>
								</ul>								
							</nav>
						</div>
					</div>
		<div class="col-md-4">
						<hr class="light">
						Software
						<hr class="light">
						<p>Html</p>
						<p>CSS</p>
						<p>Python</p>
						<p>Pandas</p>
						<p>Django</p>
					</div>
					<div class="col-12">
					<hr class="light">
					<h5>&copy; MHACKS11_Polaris.com</h5>
				</div>
			</footer>
		</body>
	</html>

polaris/templates/polaris/home.html
{% extends 'polaris/index.html' %}

polaris/templates/polaris/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}Polaris Data{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		{% block style %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
			<div class="container-fluid">
				<a class="navbar-brand" href="#"><img src="http://brand.polaris.com/wp-content/uploads/2015/11/Polaris_corpId_logos_flat_696x150.png" style="width:150px;height:40px"> RideViz
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="/">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="https://github.com/asi14/polaris-visualization">About</a>
						</li>
						<li class="nav-item">
							<a onclick = "alert('Warning: This will take a long time!')"class="nav-link" href="{% url 'world:index' %}">Google Maps Random Path Viewer</a>
						</li>
						<li class = "nav-item">
							<a class="nav-link" href = "{% url 'world:world_view'%}">Google Maps World Viewer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'contact:index' %}">Contact Us</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		{% block body %}
		<div id="slides" class="carousel slide" data-ride="carousel">
			<ul class="carousel-indicators">
				<li data-target="slides" data-slide-to="0" class="active"></li>
				<li data-target="slides" data-slide-to="1"></li>
				<li data-target="slides" data-slide-to="2"></li>
			</ul>
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img src="https://d1jgrpnx5qsq8g.cloudfront.net/images/content/1280x720/216071i37a77734d21ed0a30a98ca476c9b43eb.jpg"style="width:100%; height:100%">
					<div class="carousel-caption">
						<h1 class="display-2">Dune Buggy</h1>
					</div>
				</div>
				<div class="carousel-item">
					<img src="https://i.ytimg.com/vi/LGtB3B-Gikc/maxresdefault.jpg">
					<div class="carousel-caption">
						<h1 class="display-2">SlingShot</h1>
					</div>
				</div>
				<div class="carousel-item">
					<img src="http://cdn-gen.polaris.com/sno/2019/img/model-thumbs/indy-evo-es.png"style="width:100%; height:100%">
					<div class="carousel-caption">
						<h1 class="display-2">SnowMobile</h1>
					</div>			
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid padding">
		<div class="row welcome text-center">
			<div class="col-12">
				<h1 class="display-4" font-family:Georgia;
				font-weight: bold;>RideViz</h1>
			</div>
			<hr class="light">
			<div class="col-12">
				<p class="lead">"We created this project at MHacks 11 for Polaris'"Work Hard, Play Hard" Challenge, in which we were given a dataset of ~50,000 rides from Polaris vehicles and were tasked with creating an app or data visualization for it. We chose to create a web app that would select a random ride from the dataset each time a user accessed the site, plot its path on a Google Maps map, and present the key ride data. The backend was built with Django and the Google Maps API, the frontend was built using HTML and CSS, and we parsed/analyzed the dataset using the pandas library."</p>
			</div>
		</div>
	</div>
	<div class="container-fluid padding">
		<div class= "row text-center padding">
			<div class="col-xs-12 col-sm-6 col-md-4">
				<i class="fas fa-code"></i>
				<h3>HTML 5</h3>
				<p>Built with the latest version of HTML, HTML5.</p>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<img src="{% static 'ico/favicon.ico' %}">
				<h3>PYTHON</h3>
				<p>Built with the latest version of Python, Python.</p>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<i class="fas fa-bold"></i>
				<h3>BOOTSTRAP</h3>
				<p>Built with the latest version of Bootstrap, Bootstrap 4.</p>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<i class="fab fa-css3"></i>
				<h3>CSS3</h3>
				<p>Built with the latest version of CSS, CSS3.</p>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<img src="{% static 'ico/Panda.ico' %}">
				<h3>PANDAS</h3>
				<p>Built with the latest version of Pandas, Pandas.</p>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<img src="{% static 'ico/Dj.ico' %}">
				<h3>DJANGO</h3>
				<p>Built with the latest version of Django, Django.</p>
			</div>	
		</div>	
	</div>			
	<hr class="my-4">	
	<fiqure>
		<div class="fixed-wrap">
			<div id="fixed">
			</div>
		</div>
	</figure>
</div>	
<hr class="my-4">	
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Meet the Team</h1>
		</div>
		<hr>
	</div>
</div>


<!--- Cards -->
<div class="container-fluid padding">
	<div class="row padding">
		<div class="col-md-4">
			<div clas="card">
				<img class="card-imd-top" src="https://www.freeiconspng.com/uploads/person-icon-8.png" style="width:150px; height:150px">
				<div class="card-body">
					<h4 class="card-title">Brian</h4>
					<p class="card-text">Engineer's</p>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div clas="card">
				<img class="card-imd-top" src="https://www.freeiconspng.com/uploads/person-icon-8.png" style="width:150px; height:150px">
				<div class="card-body">
					<h4 class="card-title">Meaad</h4>
					<p class="card-text">Engineer's</p>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div clas="card">
				<img class="card-imd-top" src="https://www.freeiconspng.com/uploads/person-icon-8.png" style="width:150px; height:150px">
				<div class="card-body">
					<h4 class="card-title">Aaron</h4>
					<p class="card-text">Engineer's</p>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div clas="card">
				<img class="card-imd-top" src="https://www.freeiconspng.com/uploads/person-icon-8.png" style="width:150px; height:150px">
				<div class="card-body">
					<h4 class="card-title">Harshith</h4>
					<p class="card-text">Engineer's</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}	
<!--- Footer -->
<footer>
	<div class="container-fluid padding">
		<div class="row text-center">
			<div class="col-md-4">
				<img src="http://brand.polaris.com/wp-content/uploads/2015/11/Polaris_corpId_logos_flat_696x150.png" style="width:150px;height:40px">
				<hr class="light">
				<p>734-642-3511</p>
				<p>MHACKS11_Polaris@Mhacks.com</p>
				<p>606 E Hoover Ave</p>
				<p>Ann Arbor,MI 48104</p>
			</div>
			<div class="col-md-4">
				<hr class="light">
				Navagation
				<hr class="light">
				<div id="containers">
					<nav>
						<ul>
							<li><a class="active" href="index.html">Home</a></li>
							<li><a href="https://github.com/asi14/polaris-visualization">About</a></li>
							<li><a onclick = "alert('Warning: This will take a long time!')"class="nav-link" href="{% url 'world:index' %}">Google Maps Random Path Viewer</a></li>
							<li><a href="{% url 'world:world_view'%}">Google Maps World Viewer</a></li>
							<li><a href="Contact.html">Contact</a></li>
						</ul>								
					</nav>
				</div>
			</div>
			<div class="col-md-4">
				<hr class="light">
				Software
				<hr class="light">
				<p>Html</p>
				<p>CSS</p>
				<p>Python</p>
				<p>Pandas</p>
				<p>Django</p>
			</div>
			<div class="col-12">
				<hr class="light">
				<h5>&copy; MHACKS11_Polaris.com</h5>
			</div>
		</footer>
	</body>
	{% block javascript %}{% endblock %}
</html>

polaris/world/templates/world/map.html
	{% extends 'polaris/index.html' %}
			{% block title %}Google Maps Random Path Viewer{% endblock %}
			{% block style %}	
			<style>
			
				#map{
					height:600px;	
					width:auto;
				}
			
			</style>
			{% endblock %}
		
			{% block body %}
			<div class = "container">
				<div class = "jumbotron text-center">
					<h1>Google Maps Random Path Viewer</h1>
					<p>Click Button to Get New Path</p>
					<p>WARNING: will take significantly long time</p>
				</div>	
				<div class = "row">
					<div class = "col-md-8">
						<div id = "map"></div>
					</div>
					<div class = "col-md-4">
						<h1>Some Stats</h1>
						<p>Total Time Spent Retrieving Data: {{time_calc}}</p>
						<p>Total Duration (Seconds): {{side_values.totalDurationInSeconds}}</p>
						<p>Total Distance (Meters): {{side_values.totalDistanceInMeters}}</p>
						<p>Start Time: {{side_values.startTimestamp|date:"P; l, F j, Y"}}</p>
						<p>End Time: {{side_values.endTimestamp|date:"P; l, F j, Y"}}</p>
						<p style = "display:none" id = "location">Location: </p>
						<div class = "text-center"><button onclick = "location.reload()" type="button" class="btn btn-primary">Generate New Path</button></div>
					</div>
				</div>
				
			</div>
			{% endblock %}


		{% block javascript %}
		<script>
		
			var map;
			
			var request = new XMLHttpRequest();
			
			request.open('GET','https://maps.googleapis.com/maps/api/geocode/json?latlng={{avg_lat}},{{avg_long}}&key=AIzaSyDAiyVPTvomeKqHRKUWJFNPFZEnb808a_k')

			request.onload = function(){
				var data = JSON.parse(this.response);
				console.log(data['results']['3'])
				if(typeof data['results'][3] !== 'undefined'){
					console.log('b');
					document.getElementById('location').innerHTML = 'Location: ' + data['results'][3]['formatted_address'];	
					document.getElementById('location').style.display = 'block';	
				}
				//data.forEach(datapoint => {
					//console.log(datapoint);	
				//});	
			};

			request.send();

			function initMap() {
				map = new google.maps.Map(document.getElementById('map'), {
					center: {lat: {{avg_lat}}, lng: {{avg_long}}},
					zoom: 16
				});
				var markers = [];
				{% for coord in coords %}
					markers.push(new google.maps.Marker({position:{lat: {{coord.1}}, lng: {{coord.0}}}, map: map}));
				{% endfor %}
				
				var bounds = new google.maps.LatLngBounds();
				for(var i = 0; i < markers.length; i++){
					bounds.extend(markers[i].getPosition());	
				}
				map.fitBounds(bounds);
			}	
		
		</script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzQ6ZjhBNtsK0vpLw62SICuxjP5ca-1dI&callback=initMap"
		    async defer></script>
		{% endblock %}

polaris/world/templates/world/world_view.html
		{% extends 'polaris/index.html' %}
			{% block title %}Google Maps World Viewer{% endblock %}
			{% block style %}
			<style>
			
				#map{
					height:600px;	
					width:auto;
				}
			
			</style>
			{% endblock %}
		
			{% block body %}
			<div class = "container">
				<div class = "jumbotron text-center">
					<h1>Google Maps World Viewer</h1>
					<p>Highlights each of the car paths' locations on Planet Earth</p>
					<p class = "small">(Works only with Sample Dataset)</p>
				</div>	
				<div id = "map"></div>
			</div>
			{% endblock %}
		
		{% block javascript %}
		<script>
		
			var map;
			console.log('map var created')

			function initMap() {
				console.log('method enered')
				map = new google.maps.Map(document.getElementById('map'), {
					center: {lat: 90, lng: 90},
					zoom: 1
				});
				console.log('Map Created')

				var markers = [];
				{% for coord in average_points %}
					markers.push(new google.maps.Marker({position:{lat: {{coord.1}}, lng: {{coord.0}}}, map: map}));
				{% endfor %}
				console.log('markers laid')
				
				var bounds = new google.maps.LatLngBounds();
				for(var i = 0; i < markers.length; i++){
					bounds.extend(markers[i].getPosition());	
				}
				map.fitBounds(bounds);
			}	
		
		</script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzQ6ZjhBNtsK0vpLw62SICuxjP5ca-1dI&callback=initMap"
		    async defer></script>
			{% endblock %}